"""check_map_text.py — a read-only check that the maps' world text is English (2026-10-02, the repo in English for the public
demo). Lists every TextRenderActor whose text, and every actor label, still looks Polish; never saves a map.
(A first version fixed the signs in place: a map saved from this commandlet broke the prototype's bot, so Proto and
Training were regenerated by their build scripts instead, which write English signs.)
Run headless: UnrealEditor-Cmd.exe <uproject> -run=pythonscript -script="<abs path>" -unattended -nosplash -nullrhi
Prints MAPTEXT <map> polish_signs=N polish_labels=M per map and MAPTEXT DONE (or MAPTEXT FAIL <why>).
"""
import unreal

MAPS = ["/Game/Maps/Arena", "/Game/Maps/Training", "/Game/Maps/Proto", "/Game/Maps/Conquest"]
POLISH = set("ąćęłńóśźżĄĆĘŁŃÓŚŹŻ")
POLISH_WORDS = ("BAZA", "LINIA", "NOWA GRA", "MANEKIN", "RUCHOMY", "RAMPA", "PODEST", "CENTRUM", "WIEZA", "WIEŻA", "bez odnow")


def looks_polish(s):
    return any(c in POLISH for c in s) or any(w.lower() in s.lower() for w in POLISH_WORDS)


levels = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
actors = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
try:
    for path in MAPS:
        if not unreal.EditorAssetLibrary.does_asset_exist(path):
            print(f"MAPTEXT {path} missing")
            continue
        levels.load_level(path)
        signs, labels = 0, 0
        for a in actors.get_all_level_actors():
            if isinstance(a, unreal.TextRenderActor):
                text = str(a.get_editor_property("text_render").get_editor_property("text"))
                if looks_polish(text):
                    signs += 1
                    print(f"MAPTEXT_SIGN {path} '{text}'")
            label = a.get_actor_label()
            if looks_polish(label):
                labels += 1
                print(f"MAPTEXT_LABEL {path} {label}")
        print(f"MAPTEXT {path} polish_signs={signs} polish_labels={labels}")
    print("MAPTEXT DONE")
except Exception as ex:
    print(f"MAPTEXT FAIL {ex}")
